<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-06-12 at 11:12:23.
 */
require_once('../src/Customer.php');
class CustomerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Customer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Customer("Cristina");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Customer::addRental
     * @todo   Implement testAddRental().
     */
    public function testAddRental()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Customer::getName
     */
    public function testGetName()
    {
      $this->assertEquals($this->object->getName(), "Cristina");
    }

    /**
     * @covers Customer::statement
     * @todo   Implement testStatement().
     */
    public function testStatement(){
      $this->object->addRental(new Rental(7, new Movie(2, "Micul print")));
      $this->object->addRental(new Rental(5, new Movie(0, "Gradina uitata")));
      $this->object->addRental(new Rental(14, new Movie(1, "Cu glasul timpului")));
      echo $this->object->statement();
     // echo $this->object->htmlStatement();
    }
}
