<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-06-11 at 17:58:33.
 */
require_once('../src/Movie.php');
class MovieTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Movie
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Movie(0, "Maestrul si Margareta");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Movie::setPriceCode
     * @todo   Implement testSetPriceCode().
     */
    public function testSetPriceCode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Movie::getPriceCode
     */
    public function testGetPriceCode()
    {
      $this->assertEquals($this->object->getPriceCode(), 0);
    }

    /**
     * @covers Movie::setTitle
     * @todo   Implement testSetTitle().
     */
    public function testSetTitle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Movie::getTitle
     */
    public function testGetTitle()
    {
      $this->assertEquals($this->object->getTitle(), "Maestrul si Margareta");
    }
}
