<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-06-12 at 11:05:03.
 */
require_once('../src/Rental.php');
class RentalTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Rental
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Rental(5, new Movie(1, "Despre eroi si morminte"));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Rental::getDaysRented
     */
    public function testGetDaysRented()
    {
      $this->assertEquals($this->object->getDaysRented(), 5);
    }

    /**
     * @covers Rental::getMovie
     */
    public function testGetMovie()
    {
      $this->assertEquals($this->object->getMovie()->getPriceCode(), 2);
      $this->assertEquals($this->object->getMovie()->getTitle(), "Despre eroi si morminte");
    }
}
