<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-24 at 16:56:10.
 */
class GetCmdInterpreterTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var GetCmdInterpreter
     */
    protected $object;


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $new_group = new IniGroup();
        $new_group->SetProperty("a", 7);
        IniGroupsContainer::AddIniGroup("testIniGroup", $new_group);
        IniGroupsContainer::SetCurentIniGroup("testIniGroup");

        $this->object = new GetCmdInterpreter;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers GetCmdInterpreter::CommandInterpreter
     * @todo   Implement testCommandInterpreter().
     */
    public function testCommandInterpreter()
    {
        $this->object->SetCommandParams("a");
        $this->assertSame("testIniGroup : a = 7\n",$this->object->CommandInterpreter());
    }
}
