//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace MoodWeather.Web.SqlModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ApiListEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ApiListEntities object using the connection string found in the 'ApiListEntities' section of the application configuration file.
        /// </summary>
        public ApiListEntities() : base("name=ApiListEntities", "ApiListEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ApiListEntities object.
        /// </summary>
        public ApiListEntities(string connectionString) : base(connectionString, "ApiListEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ApiListEntities object.
        /// </summary>
        public ApiListEntities(EntityConnection connection) : base(connection, "ApiListEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WeatherPublish> WeatherPublishes
        {
            get
            {
                if ((_WeatherPublishes == null))
                {
                    _WeatherPublishes = base.CreateObjectSet<WeatherPublish>("WeatherPublishes");
                }
                return _WeatherPublishes;
            }
        }
        private ObjectSet<WeatherPublish> _WeatherPublishes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WeatherSetup> WeatherSetups
        {
            get
            {
                if ((_WeatherSetups == null))
                {
                    _WeatherSetups = base.CreateObjectSet<WeatherSetup>("WeatherSetups");
                }
                return _WeatherSetups;
            }
        }
        private ObjectSet<WeatherSetup> _WeatherSetups;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WeatherPublishes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWeatherPublishes(WeatherPublish weatherPublish)
        {
            base.AddObject("WeatherPublishes", weatherPublish);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WeatherSetups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWeatherSetups(WeatherSetup weatherSetup)
        {
            base.AddObject("WeatherSetups", weatherSetup);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ApiListModel", Name="WeatherPublish")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WeatherPublish : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WeatherPublish object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static WeatherPublish CreateWeatherPublish(global::System.Int32 id)
        {
            WeatherPublish weatherPublish = new WeatherPublish();
            weatherPublish.id = id;
            return weatherPublish;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ftp_address
        {
            get
            {
                return _ftp_address;
            }
            set
            {
                Onftp_addressChanging(value);
                ReportPropertyChanging("ftp_address");
                _ftp_address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ftp_address");
                Onftp_addressChanged();
            }
        }
        private global::System.String _ftp_address;
        partial void Onftp_addressChanging(global::System.String value);
        partial void Onftp_addressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ftp_port
        {
            get
            {
                return _ftp_port;
            }
            set
            {
                Onftp_portChanging(value);
                ReportPropertyChanging("ftp_port");
                _ftp_port = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ftp_port");
                Onftp_portChanged();
            }
        }
        private global::System.String _ftp_port;
        partial void Onftp_portChanging(global::System.String value);
        partial void Onftp_portChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ftp_user_name
        {
            get
            {
                return _ftp_user_name;
            }
            set
            {
                Onftp_user_nameChanging(value);
                ReportPropertyChanging("ftp_user_name");
                _ftp_user_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ftp_user_name");
                Onftp_user_nameChanged();
            }
        }
        private global::System.String _ftp_user_name;
        partial void Onftp_user_nameChanging(global::System.String value);
        partial void Onftp_user_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ftp_user_password
        {
            get
            {
                return _ftp_user_password;
            }
            set
            {
                Onftp_user_passwordChanging(value);
                ReportPropertyChanging("ftp_user_password");
                _ftp_user_password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ftp_user_password");
                Onftp_user_passwordChanged();
            }
        }
        private global::System.String _ftp_user_password;
        partial void Onftp_user_passwordChanging(global::System.String value);
        partial void Onftp_user_passwordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ftp_active
        {
            get
            {
                return _ftp_active;
            }
            set
            {
                Onftp_activeChanging(value);
                ReportPropertyChanging("ftp_active");
                _ftp_active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ftp_active");
                Onftp_activeChanged();
            }
        }
        private Nullable<global::System.Boolean> _ftp_active;
        partial void Onftp_activeChanging(Nullable<global::System.Boolean> value);
        partial void Onftp_activeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ApiListModel", Name="WeatherSetup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WeatherSetup : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WeatherSetup object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="api_key">Initial value of the api_key property.</param>
        public static WeatherSetup CreateWeatherSetup(global::System.Int32 id, global::System.String api_key)
        {
            WeatherSetup weatherSetup = new WeatherSetup();
            weatherSetup.id = id;
            weatherSetup.api_key = api_key;
            return weatherSetup;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                OnidChanging(value);
                ReportPropertyChanging("id");
                _id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id");
                OnidChanged();
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String api_key
        {
            get
            {
                return _api_key;
            }
            set
            {
                if (_api_key != value)
                {
                    Onapi_keyChanging(value);
                    ReportPropertyChanging("api_key");
                    _api_key = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("api_key");
                    Onapi_keyChanged();
                }
            }
        }
        private global::System.String _api_key;
        partial void Onapi_keyChanging(global::System.String value);
        partial void Onapi_keyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String api_calls
        {
            get
            {
                return _api_calls;
            }
            set
            {
                Onapi_callsChanging(value);
                ReportPropertyChanging("api_calls");
                _api_calls = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("api_calls");
                Onapi_callsChanged();
            }
        }
        private global::System.String _api_calls;
        partial void Onapi_callsChanging(global::System.String value);
        partial void Onapi_callsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String apic_call_minute
        {
            get
            {
                return _apic_call_minute;
            }
            set
            {
                Onapic_call_minuteChanging(value);
                ReportPropertyChanging("apic_call_minute");
                _apic_call_minute = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("apic_call_minute");
                Onapic_call_minuteChanged();
            }
        }
        private global::System.String _apic_call_minute;
        partial void Onapic_call_minuteChanging(global::System.String value);
        partial void Onapic_call_minuteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String api_url
        {
            get
            {
                return _api_url;
            }
            set
            {
                Onapi_urlChanging(value);
                ReportPropertyChanging("api_url");
                _api_url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("api_url");
                Onapi_urlChanged();
            }
        }
        private global::System.String _api_url;
        partial void Onapi_urlChanging(global::System.String value);
        partial void Onapi_urlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> active
        {
            get
            {
                return _active;
            }
            set
            {
                OnactiveChanging(value);
                ReportPropertyChanging("active");
                _active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("active");
                OnactiveChanged();
            }
        }
        private Nullable<global::System.Byte> _active;
        partial void OnactiveChanging(Nullable<global::System.Byte> value);
        partial void OnactiveChanged();

        #endregion

    
    }

    #endregion

    
}
